apiVersion: apps/v1 # mặc định apiVersion cho deployment
kind: Deployment
metadata:
  name: mydeployment
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mypod # the deployment manage all pods with labels matching mypod
  template:
    metadata:
      labels:
        app: mypod # labels for all the pods the deployment is managing
    spec:
      containers:
        - name: mypod
          image: nginx # các pod dùng chung image nginx nhưng instance container khác nhau
          resources:
            limits:
              memory: 600Mi
              cpu: 1
            requests:
              memory: 300Mi
              cpu: 500m