apiVersion: v1 # mặc định apiVersion cho pod
kind: Pod
metadata:
  name: mypod
  namespace: test
spec:
  containers:
    - name: mypod
      image: nginx
      resources:
        limits:
          memory: 250Mi
          cpu: 0.5
        requests:
          memory: 250Mi
          cpu: 0.5