route:
  repeat_interval: 15s # Time interval between consecutive notifications for the same alert
  receiver: discord

receivers:
- name: discord
  discord_configs:
  - webhook_url: https://discord.com/api/webhooks/1390541817661100063/DvSonkVf0y1mUwn6ZK2RogimOCPel20K7IXB7j_nuR8bTO0zBWjR_9zn1LYhrcV4VzC1